- name: Install nginx
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Install sites
  template:
    src: vhost.conf
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
    mode: "0644"
  when: item.state | default('present') == 'present'
  with_items: "{{ nginx_sites }}"
  notify: Reload nginx

- name: Enable sites
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    force: yes
    state: link
  when: item.state | default('present') == 'present'
  with_items: "{{ nginx_sites }}"
  notify: Reload nginx

- name: Disable sites
  file:
    dest: "/etc/nginx/sites-enabled/{{ item.name }}"
    state: absent
  with_items: "{{ nginx_sites }}"
  when: item.state | default('present') in ['absent', 'removed']
  notify: Reload nginx

- name: Remove sites
  file:
    dest: "/etc/nginx/sites-available/{{ item.name }}"
    state: absent
  with_items: "{{ nginx_sites }}"
  when: item.state | default('present') == 'removed'
  notify: Reload nginx

- meta: flush_handlers

- name: Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
