---
- name: Create module directory
  file:
    path: "{{ semodule_dest_dir }}"
    state: directory

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux-policy-devel

- name: Copy files
  copy:
    dest: "{{ semodule_dest_dir }}/{{ item.name | mandatory }}.te"
    src: "{{ item.src | default(omit) }}"
    content: "{{ item.content | default(omit) }}"
  with_items: "{{ semodule_items }}"
  register: semodule_copy_files

- name: compile policy files
  command: "make -f /usr/share/selinux/devel/Makefile {{ item.item.name }}.pp"
  args:
    chdir: "{{ semodule_dest_dir }}"
  with_items: "{{ semodule_copy_files.results }}"
  when: item.changed

- name: semodule
  shell: "semodule -i {{ item.item.name }}.pp"
  args:
    chdir: "{{ semodule_dest_dir }}"
  with_items: "{{ semodule_copy_files.results }}"
  when: item.changed
